package com.paypal.api.payments;

import com.paypal.base.rest.PayPalModel;
import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;

@Data
@Accessors(chain = true)
public class PayoutBatchHeader extends PayPalModel {

	/**
	 * An ID for the batch payout. Generated by PayPal. 30 characters max.
	 */
	private String payoutBatchId;

	/**
	 * Generated batch status.
	 */
	private String batchStatus;

	/**
	 * The time the batch entered processing.
	 */
	private String timeCreated;

	/**
	 * The time that processing for the batch was completed.
	 */
	private String timeCompleted;

	/**
	 * The original batch header as provided by the payment sender.
	 */
	private PayoutSenderBatchHeader senderBatchHeader;

	/**
	 * Total amount, in U.S. dollars, requested for the applicable payouts.
	 */
	private Currency amount;

	/**
	 * Total estimate in U.S. dollars for the applicable payouts fees.
	 */
	private Currency fees;

	/**
	 * 
	 */
	private Error errors;

	/**
	 * 
	 */
	private List<Links> links;

	/**
	 * Default Constructor
	 */
	public PayoutBatchHeader() {
	}

	/**
	 * Parameterized Constructor
	 */
	public PayoutBatchHeader(String payoutBatchId, String batchStatus, String timeCreated, PayoutSenderBatchHeader senderBatchHeader, Currency amount, Currency fees) {
		this.payoutBatchId = payoutBatchId;
		this.batchStatus = batchStatus;
		this.timeCreated = timeCreated;
		this.senderBatchHeader = senderBatchHeader;
		this.amount = amount;
		this.fees = fees;
	}
}
